---
platform: linux

inputs:
- name: git-dea-ci
- name: git-resource

image_resource:
  type: docker-image
  source: {repository: geoscienceaustralia/autobots-terraform}

params:
- AWS_ACCESS_KEY_ID: ((aws-access-key))
- AWS_SECRET_ACCESS_KEY: ((aws-secret-key))

run:
  path: git-dea-ci/tasks/run-terraform-task.sh